name: Go

on:
  schedule:
    - cron:  '25 1,15 * * *'

jobs:

  RUN:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: build
      run: go build ./saying.go
      
    - name: run
      run: ./saying -token ${{secrets.NOTION_TOKEN}} -bid ${{secrets.BLOCK_ID}} -did ${{secrets.DATABASE_ID}}
