name: Go

on:
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: LS
      run: echo ${{ secrets.notion_token }}
      
#     - name: RUN
#       run: go run ./saying.go
