name: Go

on:
  watch:
    types: [started]

jobs:

  RUN:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: build
      run: go build ./saying.go
      
    - name: run
      run: ./saying -token ${{NOTION_TOKEN}} -bid ${{BLOCK_ID}} -did ${{DATABASE_ID}}
